[project]
name = "querypy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pymend>=1.1.0",
    "ruff>=0.14.5",
    "pytest>=9.0.1",
]
